services:
  - type: web
    name: kannada-translator-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false